INDIVIDUAL_CHALLENGES = [
  {
    title: "QR Code Scavenger Hunt",
    details: "Your mission, should you choose to accept it, is to write love messages encoded in QR codes and strategically scatter them throughout your home. The challenge? Your partner must embark on a hunt to find and decode all the hidden QR codes! ",
    estimated_time: 3,
    difficulty: 1,
    prompt: "Before starting, inform your partner of the total number of QR codes hidden around the house. Each QR code should hold a message just waiting to be discovered. Get creative with your placements and watch as your partner deciphers each code!",
    exp: 30,
    acts_of_service: false,
    words_of_affirmation: true,
    physical_touch: false,
    quality_time: false,
    receiving_gifts: false
  },
  {
    title: "Snail Mails Shenanigans",
    details: "Get ready to put a playful spin on traditional snail mail! Your mission is to send a caring and funny letter to your partner through the good old-fashioned postal service. But here's the twist – this isn't just any ordinary love letter! You'll recieve further directives when you accept this challenge!",
    estimated_time: 2,
    difficulty: 1,
    prompt: "Choose a quirky  stationery to reflect your personality. Decorate the envelope with stickers,or funny drawings to make it stand out in the mailbox. Consider to incorporate interactive elements like pull-out tabs, pop-up illustrations, or scratch-off sections for an  extra surprise effect!  Slip in some surprise goodies like confetti, tea bags, or small treats and don't forget to seal it with a Smooch!",
    exp: 20,
    acts_of_service: true,
    words_of_affirmation: true,
    physical_touch: false,
    quality_time: false,
    receiving_gifts: false
  },
  {
    title: "Compliment Carnival",
    details: "Get ready to shower your partner with a cascade of compliments that'll make their heart dance and cheeks blush! Your mission is to deliver as many delightfully cheesy, punny, and downright hilarious (but hearthfelt) compliments to your partner throughout the week! Fill in your partners ego!",
    estimated_time: 1,
    difficulty: 2,
    prompt: "But here's the twist: to add to the fun, try slipping compliments into everyday conversations in the most absurd and unexpected ways. The goal is to spread joy while making your partner feel like a rockstar! So, lace up those comedy boots, warm up those vocal cords, and get ready to unleash a flood of compliments that'll leave your partner grinning from ear to ear!",
    exp: 10,
    acts_of_service: false,
    words_of_affirmation: true,
    physical_touch: false,
    quality_time: false,
    receiving_gifts: false
  },
  {
    title: "Movie Palooza",
    details: "Select a movie you're sure your partner will love and, then, enhance the experience with a DIY snack bar with tasty treats. Transform your couch into a throne fit for movie royalty (you only want the best for your babe).",
    estimated_time: 2,
    difficulty: 1,
    prompt: "To add some extra fun, create a game to play during the movie! Try counting how many times a special word is said (or invent your own movie-themed challenge).",
    exp: 10,
    acts_of_service: false,
    words_of_affirmation: false,
    physical_touch: false,
    quality_time: true,
    receiving_gifts: false
  },
  {
    title: "Picnic Bonanza",
    details: "Add a touch of excitement to the end of your partner's workday by surprising them with a delightful picnic waiting just outside their workplace. Whether you opt for a simple spread or go all out with gourmet treats, ensure to include their favorite snacks! ",
    estimated_time: 3,
    difficulty: 2,
    prompt: "Don't forget the little touches – bring along a fancy glass for their drink, whether it's juice or something bubbly, and lay out a comfy blanket for lounging! Above all, let your partner know how much you treasure these moments together and relish every minute of quality time shared.",
    exp: 30,
    acts_of_service: false,
    words_of_affirmation: false,
    physical_touch: false,
    quality_time: true,
    receiving_gifts: false
  },
  {
    title: "Bubbly Retreat",
    details: "Transform your bathroom into a calm retreat as you draw your partner a sumptuous bubble bath (try completing it with fragrant oils and flickering candles to create a mood). Join as soon as possible, and sink into the warm water together, feeling the stress of the day melt away as you cherish each other's company!",
    estimated_time: 1,
    difficulty: 1,
    prompt: "To add an extra touch of romance and surprise, try scatter rose petals around the bathroom, play soft music in the background, and have cool drink waiting nearby!.",
    exp: 10,
    acts_of_service: false,
    words_of_affirmation: false,
    physical_touch: true,
    quality_time: false,
    receiving_gifts: false
  },
  {
    title: "Namaste",
    details: "Surprise your partner with a couples yoga session! Dive into the world of yoga together as you explore couples' poses that promote harmony and connection. Even if you're new to yoga, don't worry - plenty of beginner-friendly tutorials are available online (or you can attend a local class). Who knows you might just find a new hobby to enjoy together?",
    estimated_time: 2,
    difficulty: 3,
    prompt: "Consider presenting your partner, before the yoga session, with a thoughtful yoga-related gift to kickstart the experience with excitement. Whether it's a personalized yoga mat, eco-friendly props, stylish activewear, or calming essential oils, choose a gift that reflects their interests and enhances their yoga practice!",
    exp: 20,
    acts_of_service: false,
    words_of_affirmation: false,
    physical_touch: true,
    quality_time: true,
    receiving_gifts: false
  },
  {
    title: "Chore-o-saurus Rex Challenge",
    details: "Get ready to lighten your partner's load! For one day, trade in your usual household tasks for your partner's to show your appreciation for their hard work. Whether it's tackling the dishes, folding laundry, or mowing the lawn, embrace their chores with enthusiasm and a smile. It's the perfect opportunity to lend a helping hand and strengthen your bond!",
    estimated_time: 3,
    difficulty: 3,
    prompt: "As you tackle your partner's household tasks you'll also become the star of your own mini-films. Whether you're scrubbing dishes, folding laundry or tidying up, use your creativity to film yourself in action. But here's the fun part - you'll portray each task in an exaggerated way, either making it look incredibly easy or hilariously difficult. Think a slow-motion dishwashing or comically struggling to fold a single sock. Don't forget to add a soundtrack and send these masterpieces to your partner!",
    exp: 30,
    acts_of_service: true,
    words_of_affirmation: false,
    physical_touch: true,
    quality_time: false,
    receiving_gifts: false
  },
  {
    title: "Morning Munchie",
    details: "Surprise your partner with a luxurious breakfast served right to their bedside, complete with all their favorite morning treats. From fluffy pancakes to crispy bacon, freshly squeezed juice and organic coffee, pull out all the stops to make your breakfast experience unforgettable!",
    estimated_time: 2,
    difficulty: 2,
    prompt: "To add an extra touch of romance, consider serving breakfast on a stylish tray, complete with a single flower in a vase, a handwritten note or a small gift. After all, nothing says 'I love you' like starting the day with a delicious surprise delivered straight to their bedside!",
    exp: 20,
    acts_of_service: true,
    words_of_affirmation: false,
    physical_touch: false,
    quality_time: false,
    receiving_gifts: true,
  },
  {
    title: "Treasure Hunt",
    details: "Plan an exciting treasure hunt for your partner. First, create a treasure map that will guide your partner to hidden surprise gifts around the house. But here's the twist – the treasure map won't be handed to them directly. Instead, you'll need to come up with a charade to lead them to the location of the map itself. Once they've deciphered your clue and found the map, they can embark on their treasure hunt adventure!",
    estimated_time: 3,
    difficulty: 2,
    prompt: "Hide small gifts or thoughtful notes in clever hiding spots throughout the house, and mark each location on the map with clues or symbols. Get creative with your hiding spots and make the hunt challenging yet fun!",
    exp: 30,
    acts_of_service: false,
    words_of_affirmation: true,
    physical_touch: false,
    quality_time: false,
    receiving_gifts: true
  },
  {
    title: "You're my special one",
    details: "Your mission is to surprise your partner with a thoughtful and creative gift while they're at work. Get ready to brainstorm unique ideas that will brighten their day and show them how much you care. Think outside the box and choose a gift that will put a smile on their face!",
    estimated_time: 1,
    difficulty: 1,
    prompt: "Consider your partners' tastes and preferences as you choose a gift! A DIY pop-up clown with a 'Love You' message? A foldable 3D postcard? Cinema, teater or concert tickets? A box with a hidden cake inside? The sky is the limit!",
    exp: 10,
    acts_of_service: false,
    words_of_affirmation: false,
    physical_touch: false,
    quality_time: false,
    receiving_gifts: true
  },
]
